#!/bin/bash

set -e

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin
cd ${GOPATH}/src/${MODULE}

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
go get github.com/Masterminds/glide
glide install

go vet $(go list ./... | grep -v vendor)
go test -v $(go list ./... | grep -v vendor)
