#!/bin/bash

set -e

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin
cd ${GOPATH}/src/${MODULE}

go get github.com/Masterminds/glide
glide install

go vet $(go list ./... | grep -v vendor)
go test $(go list ./... | grep -v vendor)
